### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Jules-JJ** [hbkhalil/C-accelerated-Diffusion-LMS#1]
Hello,
I have seen your multicomet function on the Matlab Mathworks website. I thought of using it for a university project, however I am a bit confused because I get the circle (pointers) of the objects that trace the functions, but I get no traces on the figures that Matblab shows. Is it possible to have the traces with your function? If so, how can I make them appear.

**Comment by hbkhalil** [comment]
Hi Jules, I haven’t written that function. However, I might be able to help if you share your code with me and let me know exactly what you need to do.  Kind regards. Ibrahim El khalil Harrane.Institute of sound and vibration research ISVRUniversity of Southampton. From: Jules-JJSent: 18 February 2021 20:04To: hbkhalil/C-accelerated-Diffusion-LMSCc: SubscribedSubject: [hbkhalil/C-accelerated-Diffusion-LMS] Questions (#1) Hello,I have seen your multicomet function on the Matlab Mathworks website. I thought of using it for a university project, however I am a bit confused because I get the circle (pointers) of the objects that trace the functions, but I get no traces on the figures that Matblab shows. Is it possible to have the traces with your function? If so, how can I make them appear.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Jules-JJ** [comment]
Basically my program is a model of a satellite launching from earth to the Moon.


%%%%constants%%%%
global E
global M
global TL
global n

 
E=1; %Earth mass in local units
M= 1/81.3; %Moon mass / earth mass
TL=1; %earth moon distance (basic local unit) =  3844000 km 

G = 1; % gravitation constant

n=(1+M)^(1/2); %moon pulse
r0 = 0.0175; %parking radius


% arc_min_sec to degres
A=input("angle degres: " );
Am=input("min of arc: " );
As=input("sec of arc: " );
alpha=A+Am/60 +As/3600;

% alpha=input("Alpha: "); %in degrees
%alpha = -41; -10 ;-30 ou -28

% Vin = input("Vitesse en km/s: "); %in SI 
% V =  Vin/1.017; %conversion to local units

V = 10.62;
%V=sqrt(2*G/r0);


%%%%variables

t0=0;
tf=10; %total travelling time= 73h we will use 4.375days
h=0.001; %timestep
t=(t0:h:tf);

%moon coordinates
xm=cos(n*t); 
ym=sin(n*t); 

% Initial conditions
x0=r0*sind(alpha);
y0=-r0*cosd(alpha);


v0x = V*cosd(alpha);
v0y = V*sind(alpha);

CI = [x0;v0x;y0;v0y];


%differential equation solution
[t,Y]=ode45('vtl',t,CI);

 %sat coordinates
xs = Y(:,1);
xs = xs';

ys = Y(:,3);
ys = ys';

% % %animation 
zx = zeros(1,length(t));
zy = zx;
X = [xm;xs;zx];
X = X' ;
Y = [ym;ys;zy];
Y = Y' ;

multicomet(X,Y)

**Comment by Jules-JJ** [comment]
It shows the three bodies on the graph, but I would like to get the trails (which doesn't happen).

**Comment by hbkhalil** [comment]
Sorry for the delay, I had some unexpected issues at work.I am having a look at your code, but my first intuition is to use a normal plot with hold on. I will let you know  Ibrahim El khalil Harrane.Institute of sound and vibration research ISVRUniversity of Southampton. From: Juliette JJSent: 19 February 2021 12:08To: hbkhalil/C-accelerated-Diffusion-LMSCc: hbkhalil; CommentSubject: Re: [hbkhalil/C-accelerated-Diffusion-LMS] Questions (#1) It shows the three bodies on the graph, but I would like to get the trails (which doesn't happen).—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hbkhalil** [comment]
I am trying to run your code but I am not sure what are all the parameters and nt is not defined can you send me the code with all the parameter pre-set so I can focus on the display section.? Ibrahim El khalil Harrane.Institute of sound and vibration research ISVRUniversity of Southampton. From: Juliette JJSent: 19 February 2021 12:08To: hbkhalil/C-accelerated-Diffusion-LMSCc: hbkhalil; CommentSubject: Re: [hbkhalil/C-accelerated-Diffusion-LMS] Questions (#1) It shows the three bodies on the graph, but I would like to get the trails (which doesn't happen).—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Jules-JJ** [comment]
%%%%definition des cstes%%%%
global E
global M
global TL
global n

 
E=1; % =  masse de la terre/ masse de la terre 
M= 1/81.3; %masse de la lune/ masse de la terre
TL=1; %distance terre_lune  en portion de D

G = 1; %Constande de gravitation 

n=(1+M)^(1/2); %pulsation de la Lune
r0 = 0.0175; %rayon de parking


%essai de conversion arc_min_sec vers degres
A=-41;
Am=-10;
As=-30;
alpha=A+Am/60 +As/3600;

V = 10.62;

%%%%variables

t0=0;
tf=10; %temps totale voyage = 73h on prend a 4.375j on jouera sur le pas
h=0.001;
t=(t0:h:tf);

xm=cos(n*t);
ym=sin(n*t);

% Conditions initiale
x0=r0*sind(alpha);
y0=-r0*cosd(alpha);


v0x = V*cosd(alpha);
v0y = V*sind(alpha);

CI = [x0;v0x;y0;v0y];


%résolution
[t,Y]=ode45('vtl',t,CI);

xs = Y(:,1);
xs = xs';

ys = Y(:,3);
ys = ys';

zx = zeros(1,length(t));
zy = zx;

% % %animation
X = [xm;xs;zx];
X = X' ;
Y = [ym;ys;zy];
Y = Y' ;

multicomet(X,Y)

**Comment by Jules-JJ** [comment]
i don't know what nt is :/


here is the function vtl that the program uses as well:

function dydt = vtl(t,y)
  global M
  global n
  
  xm=cos(n*t);
  ym=sin(n*t);
  
  r=(y(1).^2+y(3).^2).^(1/2);
  D=((y(1)-xm).^2+(y(3)-ym).^2)^(1/2);
  
  
  dydt = [y(2); -(y(1)/r^3) + M*(((xm-y(1))/D.^3)-xm); y(4); -(y(3)/r.^3) + M*(((ym-y(3))/D.^3)-ym)];

**Comment by hbkhalil** [comment]
I think there is a typo.Is it n*t ?? Can you just share an .m file that runs so I can have a look   Ibrahim El khalil Harrane.Institute of sound and vibration research ISVRUniversity of Southampton. From: Juliette JJSent: 25 February 2021 09:22To: hbkhalil/C-accelerated-Diffusion-LMSCc: hbkhalil; CommentSubject: Re: [hbkhalil/C-accelerated-Diffusion-LMS] Questions (#1) i don't know what nt is :/here is the function vtl that the program uses as well:function dydt = vtl(t,y)global Mglobal nxm=cos(nt);ym=sin(nt);r=(y(1).^2+y(3).^2).^(1/2);D=((y(1)-xm).^2+(y(3)-ym).^2)^(1/2);dydt = [y(2); -(y(1)/r^3) + M*(((xm-y(1))/D.^3)-xm); y(4); -(y(3)/r.^3) + M*(((ym-y(3))/D.^3)-ym)];—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
